### ISSUE TITLE
Adding an experience system

### ISSUE THREAD

**Issue by Kavignon** [Kavignon/SmartTactics#28]
While playing the game, characters in a party will be able to gain experience while facing off the AI and getting through a level. The design for the experience will have to keep in mind that at first, it should be easy to level up but as time passes, it will take longer.
By leveling up a character, players will be given the opportunity to increases the stats of their character by using skill points.
- [x] Deciding which algorithm to use to level up characters in a party
- [x] Design stats for every character type to represent their job role 
- [x] Create a view for skill update

**Comment by Kavignon** [comment]
Since the last 2 commits, both the formula to compute the experience points and the manager to distribute them have been implemented. The static interface for leveling up a character has been made and all that remains is to create it in the dynamic prototype

**Comment by Kavignon** [comment]
I'll consider the matter for the experience system as completed for now.
