### ISSUE TITLE
Complete reactive architecture

### ISSUE THREAD

**Issue by Kavignon** [Kavignon/SmartTactics#82]
- [ ]  The global game state must be updated to indulged the new views designed for the static interface
- [ ]  Make the actors persistant -> Revive an actor when the EventStream shows that an actor is dead 
- [x]  Implement an actor to manage the team's inventory 
- [x]  Implement an actor to manage the shop for buying and selling items.
        While selling or buying, it will need to update the inventory and the player's accumulated currency.
- [ ] The game supervisor is responsible to hold and update the global game state
- [x] Implement an actor to manage the team's party

**Comment by Kavignon** [comment]
Working on the battle system manager which will lead to the completion of the command and brain manager. The brain is good. Just that it was not implemented as a manager with its own protocol. That's got to change to work inside the architecture. Plus, new learning factors will be added today to move it past its actual state, making it better, as hoped.
