### ISSUE TITLE
Design static interface & study the market

### ISSUE THREAD

**Issue by Kavignon** [Kavignon/SmartTactics#85]
To be able to understand the needs of the players, the developer must beforehand make some research with the market. This way, I'll be able to tell what the players are looking for when they're trying out my game. 
To do so, I will need to design 2-3 different views of each available screens in the game and establish a list of tasks to perform in said interfaces. Before testing with users, each task should be vetted to see what would be the average time to complete it and if its completion would be impacted by the type of users the tester is (neophyte or an adept of the tactical RPGs). Finally, while they're testing the interface, record their thoughts on the interface and see what adjustment(s) must be made in order to have a better prototype on a mobile platform.

**Comment by Kavignon** [comment]
The screens are designed and looked good enough to validate with potential users. 
All that remains is 
- [x] Make a list of tasks to complete in the static interface 
- [x] Have a form to question the user and see in which category of player he/she fits in
- [x]  Evaluate the amount of time each task should take 
- [ ]  Make adjustments to the initial design

**Comment by Kavignon** [comment]
So, I've met a few play testers Friday the 25th. They were able to perform the tasks that were given. They had some comments on how the interface should be presented, such as when every information was set when creating the avatar for a new game, the confirm button should "lit" up to make sure we don't miss it. The way buttons were organized was misleading a few times, but like I've mentioned, adjusted will be made accordingly to the comments for the final design of the first prototype.
